config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end 
  end

  resources :tweets, only: [:create, :destroy, :edit, :show]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  # get 'sessions/new'
  # get 'page/home'
  root 'page#home'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  content    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Tweet < ApplicationRecord

    belongs_to :user

    validates :content, presence: true, length: { maximum: 140 }
    validates :user_id, presence: true

    default_scope -> { order(created_at: :desc) }

    
    scope :from_users_followed_by, lambda { |user| followed_by(user) }

    private 

    def self.followed_by(user)
      followed_ids = %(SELECT followed_id FROM relationships
                       WHERE follower_id = :user_id)
        where("user_id IN (#{followed_ids}) OR user_id = :user_id", { :user_id => user })
    end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:edit, :destroy]
  before_action :authorized, only: :destroy

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

      if @tweet.save
        flash[:success] = "Tweet was successfully posted."
        redirect_to root_path
      else
        flash[:notice] = "Tweet is invalid."
        redirect_to root_path
      end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
      flash[:notice] = "Tweet was successfully destroyed."
      redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end

    def authorized
      redirect_to root_path unless current_user(@tweet.user)
    end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: @tweet, local: true) do |form| %>

   <% if form.object.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this tweet from being saved:</h2>
      <ul>
        <% form.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :tweet_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= link_to tweet.content, tweet %></td>
        <td><%= link_to tweet.user.name, tweet.user %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <% if @tweets.size == 0 %>
    <em>No tweets found</em>
  <% end %>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><h1>Tweet:</h1></strong>
  <%= @tweet.content %>
</p>
<p>Posted by <%= @tweet.user.name%> <%= time_ago_in_words(@tweet.created_at) %> ago.</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<% if current_user?(@tweet.user) %>
<%= link_to "delete", @tweet, :method => :delete, :confirm => "You sure?" %> 
<% end %> | 
<%= link_to 'Back', user_path(@tweet.user) %>