config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end 
  end

  resources :tweets, only: [:create, :destroy, :edit, :show]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  # get 'sessions/new'
  # get 'page/home'
  root 'page#home'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  handle             :string
#  name               :string
#  encrypted_password :string
#  email              :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class User < ApplicationRecord

    attr_accessor :password

    before_save :encrypt_password

    has_many :tweets, dependent: :destroy
    has_many :relationships, foreign_key: "follower_id", dependent: :destroy
    has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy
    has_many :following, through: :relationships, source: :followed
    has_many :followers, through: :reverse_relationships, source: :follower

    validates :name, presence: true, length: { maximum: 50 }
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: email_regex }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, confirmation: true, length: { minimum: 8}
    validates :follower_id, presence: true
    validates :followed_id, presence: true

    def has_password?(submitted_password)
        encrypted_password == encrypt(submitted_password)
    end

    def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end

    def self.authenticate_with_salt(id, cookie_salt) 
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
    end

    def following?(followed) 
        relationships.find_by_followed_id(followed)
    end

    def follow!(followed) 
        relationships.create!(:followed_id => followed.id)
    end

    def unfollow!(followed) 
        relationships.find_by_followed_id(followed).destroy
    end

    def feed
        Tweet.from_users_followed_by(self)
    end

    private

        def encrypt_password
            self.salt = make_salt if new_record? 
            self.encrypted_password = encrypt(password)
        end
    
        def encrypt(string) 
            secure_hash("#{salt}--#{string}")
        end
    
        def make_salt 
            secure_hash("#{Time.now.utc}--#{password}")
        end
    
        def secure_hash(string) 
            Digest::SHA2.hexdigest(string)
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :following, :followers]
  before_action :authenticate, except: [:show, :new, :create]
  before_action :correct_user, only: [:edit, :update]

  # GET /users
  # GET /users.json
  def index
	@users = User.all
	#@users = User.paginate(page: params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
	@title = "Sign Up"
	@user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
	@user = User.new(user_params)

	# respond_to do |format|
	  if @user.save
		# format.html {
		flash[:success] = "User was successfully created."
		  redirect_to @user
		  
		# format.json { render :show, status: :created, location: @user }
	  else
		# format.html {
		   render :new
		# format.json { render json: @user.errors, status: :unprocessable_entity }
	  end
	# end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
   # respond_to do |format|
	  if @user.update(user_params)
		#format.html {
		redirect_to @user
		flash[:succes] = "User was successfully updated."
		#format.json { render :show, status: :ok, location: @user }
	  else
		#format.html {
		render :edit
	  #  format.json { render json: @user.errors, status: :unprocessable_entity }
	  end
	#end
  end

  # DELETE /users/1
  # DELETE /users/1.json
 
  def destroy
	@user.destroy
#	respond_to do |format|
	  #format.html { 
		  flash[:success] = "User was successfully destroyed."
		redirect_to root_url
		
	  #format.json { head :no_content }
	#end
  end

	def following
    @title = "Following"
    @users = @user.following.all
    render 'show_follow'
	end

	def followers
		@title = "Followers"
		@users = @user.followers.all
	end

  private
	# Use callbacks to share common setup or constraints between actions.
	def set_user
	  @user = User.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def user_params
	  params.require(:user).permit(:handle, :name, :password, :email)
	end

	def correct_user
	  @user = User.find(params[:id])
	  redirect_to root_path unless current_user?(@user)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id) do |f| %>
    <div>
        <%= f.hidden_field :followed_id %>
    </div>
    <div>
        <%= f.submit "Follow" %>
    </div> 
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div>
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %> 
        <% else %>
            <%= render 'follow' %> 
        <% end %>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :handle %><br>
    <%= form.text_field :handle, id: :user_handle %>
  </div>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "Confirmation" %><br>
    <%= form.password_field :password_confirmation%>
  </div>

  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
  
  <br>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user), :html => { :method => :delete } do |f| %>
    <div>
        <%= f.submit "Unfollow" %>
    </div> 
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Handle</th>
      <th>Email</th>>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.handle %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
    <% if @users.size == 0 %>
      <em>No users found</em>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Handle:</strong>
  <%= @user.handle %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong> <%= link_to 'Following', following_user_path(@user)%>: </strong>
  <%= @user.following.count%>
</p>

<p>
  <strong> <%= link_to 'Followers', followers_user_path(@user)%>: </strong>
  <%= @user.followers.count%>
</p>

<p>
  <strong>Tweets:</strong> 
  <%= @user.tweets.count %>
</p>


<%= render 'follow_form' if signed_in? %>

<%= link_to 'Back', users_path %>

<br>
<br>

<tbody>
  <h1>Tweets</h1>
  <% @user.tweets.each do |tweet| %>
      <table>
      
      <tr>
        <td>-- <%= link_to tweet.content, tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
      </table>
    <% end %>
    <% if @user.tweets.size == 0 %>
      <em>No tweets yet</em>
    <% end %> 
</tbody>

app/views/users/show_follow.html.erb
<table>
    <tr>
        <td>
            <h1>
                <%= @title %>
            </h1>
            <% unless @users.empty? %>
                <ul>
                    <% @users.each do |user| %>
                        <%= link_to user.name, user%>
                    <% end %>
                </ul>
            <% end %>
        </td>
    </tr>
</table>