config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end 
  end

  resources :tweets, only: [:create, :destroy, :edit, :show]
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  # get 'sessions/new'
  # get 'page/home'
  root 'page#home'
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  delete 'signout' => 'sessions#destroy'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>
        <%= @title %>
    </title>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag "application" %>
</head>

<body>

    <div>
        <header>
            <nav>
                <ul>
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <% if signed_in? %>
                        <li><%= link_to "Users", users_path %></li> 
                        <li><%= link_to "Settings", edit_user_path(current_user) %></li> 
                        <li><%= link_to 'Deactivate', current_user, method: :delete, data: { confirm: 'Are you sure?' } %></li> 
                        <li><%= link_to "Sign out", signout_path, :method => :delete %></li> 
                    <% else %>
                        <li><%= link_to "Sign in", signin_path %></li>
                        <li>
                        <%= link_to "Sign up", new_user_path %>
                        </li>
                    <% end %>
                </ul>
            </nav>
        </header>
        <section>
            <% flash.each do |key, value| %>
                <div><%= value %></div>
            <% end %>
        </section>
        <section>
            <%= yield %>
        </section>
    </div>
</body>

</html>